// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/joiner-home/FamilyWall.tsx": () => import("../components/mockups/joiner-home/FamilyWall.tsx"),
  "./components/mockups/joiner-home/ObserverFeed.tsx": () => import("../components/mockups/joiner-home/ObserverFeed.tsx"),
  "./components/mockups/joiner-home/StatusDashboard.tsx": () => import("../components/mockups/joiner-home/StatusDashboard.tsx"),
  "./components/mockups/joiner-home/TodaysStory.tsx": () => import("../components/mockups/joiner-home/TodaysStory.tsx")
};
